### ISSUE TITLE
Ensure full compatibility with JS version

### ISSUE THREAD

**Issue by glouvigny** [berty/go-orbit-db#9]

**Comment by NokiDev** [comment]
Hi, 
could you provide the actual state of compatibility between js and go ?
I was not able to make each other talk yet, it's probably, due to an "old" orbitdb address, but I didnt have the time to debug it properly so far. 
If anyone has an advice or achieve to do it, please good you explain a bit here 

Thank you so much in advance

**Comment by sashahilton00** [comment]
From what I can see, there are at least a couple of models (feed, docs, possibly counter) that have yet to be implemented in this implementation, so I imagine that might cause some compatibility issues

**Comment by glouvigny** [comment]
Hi,

At this stage the compatibility between both versions has not been the main focus at @berty, it hasn't been tested and we can't guarantee that it works.

Regarding this issue two things need to be checked, features and compatibility.

As @sashahilton00 mentioned, some stores (feed, docs, counter) are not implemented. Same with access controllers, for example those relying on ethereum. The missing features mean that you can't open a store require them as it will throw an error.

The other thing which should be tested is that a JS client can talk to a Go one, can load a datastore created from the other implementation, use an address across both versions etc.

**Comment by jefft0** [comment]
We plan to rewrite go-orbit-db and compatibility with the JS version isn't a focus.
